AvgSpeed <- c(60, 70, 65, 80, 75)   
TotalTime <- c(100, 120, 110, 90, 95) 
std_dev_AvgSpeed <- sd(AvgSpeed)
std_dev_TotalTime <- sd(TotalTime)
cat("Standard Deviation of AvgSpeed:", std_dev_AvgSpeed, "\n")
cat("Standard Deviation of TotalTime:", std_dev_TotalTime, "\n")
variance_AvgSpeed <- var(AvgSpeed)
variance_TotalTime <- var(TotalTime)
cat("Variance of AvgSpeed:", variance_AvgSpeed, "\n")
cat("Variance of TotalTime:", variance_TotalTime, "\n")
